# Generated by Django 5.2.6 on 2025-09-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField()),
                ('api_key', models.TextField()),
                ('rate_limit_per_hour', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CacheMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('service_name', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key'], name='services_ca_cache_k_9f14f0_idx'), models.Index(fields=['expires_at'], name='services_ca_expires_6c05ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_called', models.CharField(max_length=255)),
                ('response_status', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cached', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.thirdpartyservice')),
            ],
            options={
                'indexes': [models.Index(fields=['service', 'timestamp'], name='services_ap_service_144573_idx'), models.Index(fields=['user', 'timestamp'], name='services_ap_user_id_9d9ffc_idx')],
            },
        ),
    ]
